"""Inventory item attributes to lists

Revision ID: 514ee32c73da
Revises: 5cfbadab61f7
Create Date: 2024-05-10 22:00:31.724400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514ee32c73da'
down_revision = '5cfbadab61f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column('inventories', sa.Column('items', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column('inventories', sa.Column('items_required', sa.Text(), nullable=False, server_default='[]'))
        batch_op.drop_column('inventories', 'q4_required')
        batch_op.drop_column('inventories', 'q3_required')
        batch_op.drop_column('inventories', 'q6_required')
        batch_op.drop_column('inventories', 'q1')
        batch_op.drop_column('inventories', 'q2_required')
        batch_op.drop_column('inventories', 'q1_required')
        batch_op.drop_column('inventories', 'q5_required')
        batch_op.drop_column('inventories', 'q9_required')
        batch_op.drop_column('inventories', 'q5')
        batch_op.drop_column('inventories', 'q7_required')
        batch_op.drop_column('inventories', 'q9')
        batch_op.drop_column('inventories', 'q8')
        batch_op.drop_column('inventories', 'q10_required')
        batch_op.drop_column('inventories', 'q6')
        batch_op.drop_column('inventories', 'q2')
        batch_op.drop_column('inventories', 'q10')
        batch_op.drop_column('inventories', 'q4')
        batch_op.drop_column('inventories', 'q3')
        batch_op.drop_column('inventories', 'q8_required')
        batch_op.drop_column('inventories', 'q7')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('q7', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q8_required', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q3', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q4', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q10', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q2', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q6', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q10_required', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q8', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q9', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q7_required', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q5', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q9_required', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q5_required', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q1_required', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q2_required', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q1', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q6_required', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q3_required', sa.INTEGER(), nullable=False))
    op.add_column('inventories', sa.Column('q4_required', sa.INTEGER(), nullable=False))
    op.drop_column('inventories', 'items_required')
    op.drop_column('inventories', 'items')
    # ### end Alembic commands ###
