"""Offers as thread child

Revision ID: 5b6b5fb80a4c
Revises: 514ee32c73da
Create Date: 2024-05-11 10:55:31.147215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6b5fb80a4c'
down_revision = '514ee32c73da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('thread_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'offers', 'threads', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'thread_id')
    # ### end Alembic commands ###
