"""Initial migration

Revision ID: 5cfbadab61f7
Revises: 
Create Date: 2024-05-10 21:18:03.003830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfbadab61f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.Column('request_body', sa.String(length=200), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('error_response_body', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('authentication_token', sa.String(length=200), nullable=True),
    sa.Column('change_password_token', sa.String(length=200), nullable=True),
    sa.Column('security_question', sa.String(length=200), nullable=False),
    sa.Column('security_question_answer', sa.String(length=200), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_expiry', sa.DateTime(), nullable=True),
    sa.Column('loot_drop_refresh', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('q1', sa.Integer(), nullable=False),
    sa.Column('q1_required', sa.Integer(), nullable=False),
    sa.Column('q2', sa.Integer(), nullable=False),
    sa.Column('q2_required', sa.Integer(), nullable=False),
    sa.Column('q3', sa.Integer(), nullable=False),
    sa.Column('q3_required', sa.Integer(), nullable=False),
    sa.Column('q4', sa.Integer(), nullable=False),
    sa.Column('q4_required', sa.Integer(), nullable=False),
    sa.Column('q5', sa.Integer(), nullable=False),
    sa.Column('q5_required', sa.Integer(), nullable=False),
    sa.Column('q6', sa.Integer(), nullable=False),
    sa.Column('q6_required', sa.Integer(), nullable=False),
    sa.Column('q7', sa.Integer(), nullable=False),
    sa.Column('q7_required', sa.Integer(), nullable=False),
    sa.Column('q8', sa.Integer(), nullable=False),
    sa.Column('q8_required', sa.Integer(), nullable=False),
    sa.Column('q9', sa.Integer(), nullable=False),
    sa.Column('q9_required', sa.Integer(), nullable=False),
    sa.Column('q10', sa.Integer(), nullable=False),
    sa.Column('q10_required', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('offering', sa.Text(), nullable=False),
    sa.Column('wanting', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('threads')
    op.drop_table('offers')
    op.drop_table('inventories')
    op.drop_table('users')
    op.drop_table('logs')
    # ### end Alembic commands ###
