"""utc timestamps

Revision ID: 6d79d95db4de
Revises: c0d97aaa0fd4
Create Date: 2024-05-16 16:55:43.137488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d79d95db4de'
down_revision = 'c0d97aaa0fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_level_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('_loot_drop_refresh', sa.DateTime(), nullable=True))
        batch_op.drop_column('loot_drop_refresh')
        batch_op.drop_column('level_expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_expiry', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('loot_drop_refresh', sa.DATETIME(), nullable=True))
        batch_op.drop_column('_loot_drop_refresh')
        batch_op.drop_column('_level_expiry')

    # ### end Alembic commands ###
