"""Offers as thread child

Revision ID: c0d97aaa0fd4
Revises: 514ee32c73da
Create Date: 2024-05-11 16:36:18.663282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d97aaa0fd4'
down_revision = '514ee32c73da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_offers_threads_thread_id', 'threads', ['thread_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_offers_threads_thread_id', type_='foreignkey')
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
